#############################################################################
#                                                                           #
# appveyor.yml                                                              #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################

# common configuration for ALL branches
image: Visual Studio 2019

environment:
  COVERALLS_REPO_TOKEN:  
    secure: bvDUvtlcBmb6yo4vcpSGU1ux9fsIT2Bcq/uEMZYANh93Yc+FuQf7qjjCNSsro7Id
  GITHUB_REPO_TOKEN:
    secure: qJEufJv866eebR/Boe1UnV3p1arOIX9BTyqAQnAVY49h4Ks40Sr0rHb3iN70e7BZ
  NUGET_REPO_TOKEN:
    secure: ZuEDRRTkWs7MykjAL2l/1eE0t0iilg3L4Eu1bu/EswIeaTytjUiPsqo8BTeMofd8
  GITHUB_EMAIL:
    secure: Z6F+xZzdZzc5DMYB/4J0KUhyoTzTlXH75ciGl7hFH9s=
  APPVEYOR_RDP_PASSWORD:
    secure: IvxSZoWD+DpqNjUP7mFjPA==

branches:
  # blacklist
  except:
    - gh-pages

# prevent MSBuild from running
build: off

clone_script:
  - cmd: |
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      git checkout -qf %APPVEYOR_REPO_COMMIT%
      
# enable RDP
init:
  - ps: IEX ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# "before_test" runs after repo cloning so use it instead of "init"
before_test:
  - ps: |
      Set-Location -Path ".\SCRIPTS"
      .(".\includes.ps1")
      Update-AppveyorBuild -Version "$($PROJECT.version).$($Env:APPVEYOR_BUILD_NUMBER)-$($Env:APPVEYOR_REPO_BRANCH)"
      Get-SysInfo

test_script:
  - ps: Test

after_test:
  - ps: Push-Test-Results

# after build failure or success
on_finish:
  - ps: |
      Push-Artifact "*.txt"
      Push-Artifact "BenchmarkDotNet.Artifacts\BenchmarkRun-*.log"
      $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# override settings for `master` branch
for:
-
  branches:
    only:
      - master

  before_deploy:
    - ps: Git-Config 
  
  deploy_script: 
    # update documentation & publish nuget package
    - ps: |
        GH-Pages
        Deploy