//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solti.Utils.Rpc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solti.Utils.Rpc.Properties.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one methods are annotated with the same verb..
        /// </summary>
        internal static string AMBIGOUS_TARGET {
            get {
                return ResourceManager.GetString("AMBIGOUS_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByRef parameters are not supported..
        /// </summary>
        internal static string BYREF_PARAMETER {
            get {
                return ResourceManager.GetString("BYREF_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more dependencies are not available: {0}.
        /// </summary>
        internal static string DEPENDENCY_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("DEPENDENCY_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more dependencies are not running..
        /// </summary>
        internal static string DEPENDENCY_NOT_RUNNING {
            get {
                return ResourceManager.GetString("DEPENDENCY_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic interfaces are not supported..
        /// </summary>
        internal static string GENERIC_IFACE {
            get {
                return ResourceManager.GetString("GENERIC_IFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type not supported..
        /// </summary>
        internal static string HTTP_CONTENT_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("HTTP_CONTENT_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Encoding not supported..
        /// </summary>
        internal static string HTTP_ENCODING_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("HTTP_ENCODING_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http method not supported..
        /// </summary>
        internal static string HTTP_METHOD_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("HTTP_METHOD_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the args array does not match the parameter count..
        /// </summary>
        internal static string INAPPROPRIATE_ARRAY_LENGTH {
            get {
                return ResourceManager.GetString("INAPPROPRIATE_ARRAY_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller does not have sufficient privileges to invoke the method..
        /// </summary>
        internal static string INSUFFICIENT_PRIVILEGES {
            get {
                return ResourceManager.GetString("INSUFFICIENT_PRIVILEGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;netsh&quot; invocation failed..
        /// </summary>
        internal static string NETSH_INVOCATION_FAILED {
            get {
                return ResourceManager.GetString("NETSH_INVOCATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compatible hosting found..
        /// </summary>
        internal static string NO_HOSTING {
            get {
                return ResourceManager.GetString("NO_HOSTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request must specify a module method..
        /// </summary>
        internal static string NO_METHOD {
            get {
                return ResourceManager.GetString("NO_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request must specify a module..
        /// </summary>
        internal static string NO_MODULE {
            get {
                return ResourceManager.GetString("NO_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no RequiredRoles attribute specified for the module method {0}..
        /// </summary>
        internal static string NO_ROLES_SPECIFIED {
            get {
                return ResourceManager.GetString("NO_ROLES_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON string must represent an array..
        /// </summary>
        internal static string NOT_AN_ARRAY {
            get {
                return ResourceManager.GetString("NOT_AN_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module must be an interface..
        /// </summary>
        internal static string NOT_AN_INTERFACE {
            get {
                return ResourceManager.GetString("NOT_AN_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target method should not contain any parameters..
        /// </summary>
        internal static string NOT_PARAMETERLESS {
            get {
                return ResourceManager.GetString("NOT_PARAMETERLESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Control Manager invocation failed. Error {0}.
        /// </summary>
        internal static string SC_INVOCATION_FAILED {
            get {
                return ResourceManager.GetString("SC_INVOCATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme not supported..
        /// </summary>
        internal static string SCHEME_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("SCHEME_NOT_SUPPORTED", resourceCulture);
            }
        }
    }
}
