//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solti.Utils.Rpc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solti.Utils.Rpc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByRef parameters are not supported..
        /// </summary>
        internal static string BYREF_PARAMETER {
            get {
                return ResourceManager.GetString("BYREF_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic interfaces are not supported..
        /// </summary>
        internal static string GENERIC_IFACE {
            get {
                return ResourceManager.GetString("GENERIC_IFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the args array does not match with the parameter count..
        /// </summary>
        internal static string INAPPROPRIATE_ARRAY_LENGTH {
            get {
                return ResourceManager.GetString("INAPPROPRIATE_ARRAY_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;netsh&quot; invocation failed..
        /// </summary>
        internal static string NETSH_INVOCATION_FAILED {
            get {
                return ResourceManager.GetString("NETSH_INVOCATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request must specify a method..
        /// </summary>
        internal static string NO_METHOD {
            get {
                return ResourceManager.GetString("NO_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request must specify a module..
        /// </summary>
        internal static string NO_MODULE {
            get {
                return ResourceManager.GetString("NO_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON string must represent an array..
        /// </summary>
        internal static string NOT_AN_ARRAY {
            get {
                return ResourceManager.GetString("NOT_AN_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module must be an interface..
        /// </summary>
        internal static string NOT_AN_INTERFACE {
            get {
                return ResourceManager.GetString("NOT_AN_INTERFACE", resourceCulture);
            }
        }
    }
}
