//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solti.Utils.Rpc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Trace {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Trace() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solti.Utils.Rpc.Properties.Trace", typeof(Trace).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin request processing..
        /// </summary>
        internal static string BEGIN_REQUEST_PROCESSING {
            get {
                return ResourceManager.GetString("BEGIN_REQUEST_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener thread  ({0}) stopped due to an unhandled exception: ({1}).
        /// </summary>
        internal static string EXCEPTION_IN_LISTENER_THREAD {
            get {
                return ResourceManager.GetString("EXCEPTION_IN_LISTENER_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener thread ({0}) started..
        /// </summary>
        internal static string LISTENER_THREAD_STARTED {
            get {
                return ResourceManager.GetString("LISTENER_THREAD_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener thread  ({0}) stopped..
        /// </summary>
        internal static string LISTENER_THREAD_STOPPED {
            get {
                return ResourceManager.GetString("LISTENER_THREAD_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preflight request, processor won&apos;t be called..
        /// </summary>
        internal static string PREFLIGHT_REQUEST {
            get {
                return ResourceManager.GetString("PREFLIGHT_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request available..
        /// </summary>
        internal static string REQUEST_AVAILABLE {
            get {
                return ResourceManager.GetString("REQUEST_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request processed successfully..
        /// </summary>
        internal static string REQUEST_PROCESSED {
            get {
                return ResourceManager.GetString("REQUEST_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request processing failed..
        /// </summary>
        internal static string REQUEST_PROCESSING_FAILED {
            get {
                return ResourceManager.GetString("REQUEST_PROCESSING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is running... Press Ctrl+C to terminate!.
        /// </summary>
        internal static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service started..
        /// </summary>
        internal static string SERVICE_STARTED {
            get {
                return ResourceManager.GetString("SERVICE_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service terminated..
        /// </summary>
        internal static string SERVICE_TERMINATED {
            get {
                return ResourceManager.GetString("SERVICE_TERMINATED", resourceCulture);
            }
        }
    }
}
